### ISSUE TITLE
Stack size exceeded

### ISSUE THREAD

**Issue by badoualy** [enricostara/telegram-mt-node#9]
Hi,

tried to getHistory for a given chat, got the following : 

```
undefined:87
	this.readBytes = function readBytes() {
	                                   ^
RangeError: Maximum call stack size exceeded
    at readBytes (eval at createConstructor (c:\Users\Yann\Desktop\telegram\node_modules\telegram.link\node_modules\telegram-tl-node\lib\builder\constructor-builder.js:115:27), <anonymous>:87:37)
    at readBytes (eval at createConstructor (c:\Users\Yann\Desktop\telegram\node_modules\telegram.link\node_modules\telegram-tl-node\lib\builder\constructor-builder.js:115:27), <anonymous>:88:21)
    at readBytes (eval at createConstructor (c:\Users\Yann\Desktop\telegram\node_modules\telegram.link\node_modules\telegram-tl-node\lib\builder\constructor-builder.js:115:27), <anonymous>:88:21)
    at readBytes (eval at createConstructor (c:\Users\Yann\Desktop\telegram\node_modules\telegram.link\node_modules\telegram-tl-node\lib\builder\constructor-builder.js:115:27), <anonymous>:88:21)
    at readBytes (eval at createConstructor (c:\Users\Yann\Desktop\telegram\node_modules\telegram.link\node_modules\telegram-tl-node\lib\builder\constructor-builder.js:115:27), <anonymous>:88:21)
    at readBytes (eval at createConstructor (c:\Users\Yann\Desktop\telegram\node_modules\telegram.link\node_modules\telegram-tl-node\lib\builder\constructor-builder.js:115:27), <anonymous>:88:21)
    at readBytes (eval at createConstructor (c:\Users\Yann\Desktop\telegram\node_modules\telegram.link\node_modules\telegram-tl-node\lib\builder\constructor-builder.js:115:27), <anonymous>:88:21)
    at readBytes (eval at createConstructor (c:\Users\Yann\Desktop\telegram\node_modules\telegram.link\node_modules\telegram-tl-node\lib\builder\constructor-builder.js:115:27), <anonymous>:88:21)
    at readBytes (eval at createConstructor (c:\Users\Yann\Desktop\telegram\node_modules\telegram.link\node_modules\telegram-tl-node\lib\builder\constructor-builder.js:115:27), <anonymous>:88:21)
    at readBytes (eval at createConstructor (c:\Users\Yann\Desktop\telegram\node_modules\telegram.link\node_modules\telegram-tl-node\lib\builder\constructor-builder.js:115:27), <anonymous>:88:21)
```

It happens with a limit of 5 messages, tell me if you need more logs

**Comment by enricostara** [comment]
Hi @badoualy,

I released a new version and now you should be able to properly call the messages.getHistory method with the right arguments, see [here](https://rawgit.com/enricostara/telegram.link/master/doc/messages.html#section-14)

Let me know!

**Comment by badoualy** [comment]
I updated, but I still have the same issue.
The object I send is
```
{ user_id: 113326474,
  _writeBuffers: [],
  _writeOffset: 0,
  id: 'e8db2310',
  typeName: 'api.type.InputPeerContact',
  serialize: [Function: serialize],
  deserialize: [Function: deserialize],
  writeUser_id: [Function: writeUser_id],
  readUser_id: [Function: readUser_id] }
```

I also tried with an InputPeerChat, not working either

**Comment by enricostara** [comment]
I found the problem, it was when in your message-history occurs a message with a photo.
There was a very old bug in `telegram-tl-node` module, I fixed it.. 

Let me know!

**Comment by badoualy** [comment]
Fixed indeed ! Awesome ! Thanks !
